/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2024-12-18 05:59:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.marker;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.spring.domain.Member;

public final class addMarkerJS_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/LSH/%5BProject%5DFoodTrip/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FoodTrip/WEB-INF/lib/spring-webmvc-5.3.19.jar!/META-INF/spring-form.tld", Long.valueOf(1649808142000L));
    _jspx_dependants.put("/WEB-INF/views/menu/menu.jsp", Long.valueOf(1734490594000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.19.jar", Long.valueOf(1731465170589L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.spring.domain.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/FoodTrip/resources/css/menu.css\"/>\r\n");
      out.write("<style>\r\n");
      out.write(" 	.wrap {position: absolute;left: 0;bottom: 40px;width: 288px;height: 132px;margin-left: -144px;text-align: left;overflow: hidden;font-size: 12px;font-family: 'Malgun Gothic', dotum, '돋움', sans-serif;line-height: 1.5;}\r\n");
      out.write("    .wrap * {padding: 0;margin: 0;}\r\n");
      out.write("    .wrap .info {width: 286px;height: 120px;border-radius: 5px;border-bottom: 2px solid #ccc;border-right: 1px solid #ccc;overflow: hidden;background: #fff;}\r\n");
      out.write("    .wrap .info:nth-child(1) {border: 0;box-shadow: 0px 1px 2px #888;}\r\n");
      out.write("    .info .title {padding: 5px 0 0 10px;height: 30px;background: #eee;border-bottom: 1px solid #ddd;font-size: 18px;font-weight: bold;}\r\n");
      out.write("    .info .close {position: absolute;top: 10px;right: 10px;color: #888;width: 17px;height: 17px;background: url('https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/overlay_close.png');}\r\n");
      out.write("    .info .close:hover {cursor: pointer;}\r\n");
      out.write("    .info .body {position: relative;overflow: hidden;}\r\n");
      out.write("    .info .desc {position: relative;margin: 13px 0 0 90px;height: 75px;}\r\n");
      out.write("    .desc .ellipsis {overflow: hidden;text-overflow: ellipsis;white-space: nowrap;}\r\n");
      out.write("    .desc .jibun {font-size: 11px;color: #888;margin-top: -2px;}\r\n");
      out.write("    .info .img {position: absolute;top: 6px;left: 5px;width: 73px;height: 71px;border: 1px solid #ddd;color: #888;overflow: hidden;}\r\n");
      out.write("    .info:after {content: '';position: absolute;margin-left: -12px;left: 50%;bottom: 0;width: 22px;height: 12px;background: url('https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/vertex_white.png')}\r\n");
      out.write("    .info .link {color: #5085BB;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   HttpSession session = request.getSession(false);
   Member sessionId = null;
   String adminCheck = null;
   if(session != null){
      sessionId = (Member)session.getAttribute("sessionId");
      adminCheck = (String)sessionId.getNickName();
      System.out.println("게시글 작성 폼 세션 널아님!!");
      System.out.println("닉네임 : " + sessionId.getNickName());
      System.out.println("참거짓 : " + sessionId != null);
      System.out.println("참거짓 : " + adminCheck.equals("admin"));
   }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"display:flex\">\r\n");
   if(sessionId != null && adminCheck.equals("admin")){ 
      out.write("\r\n");
      out.write("   <div id=\"menublock\">\r\n");
      out.write("      <a href=\"/FoodTrip/marker/test\">마커 생성</a>\r\n");
      out.write("      <a href=\"/FoodTrip/marker/readalljson\">마커 전체 가져오기</a>\r\n");
      out.write("      <a href=\"/FoodTrip/road/makeRoad\">코스 생성</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");
} 
      out.write("\r\n");
      out.write("   <div id=\"menublock\">\r\n");
      out.write("      <a href=\"/FoodTrip/road/readRoad\">코스 전체보기</a>\r\n");
      out.write("      <a href=\"/FoodTrip/board/boards\">리뷰게시판</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"menublock\">\r\n");
      out.write("      ");

      if(sessionId != null && sessionId.getNickName() != null && !sessionId.getNickName().isEmpty()){
      
      out.write("\r\n");
      out.write("         <a href=\"/FoodTrip/member/logout\">로그아웃</a>\r\n");
      out.write("         <a href=\"/FoodTrip/member/update\">회원정보수정</a>\r\n");
      out.write("      ");
}else{
      out.write("\r\n");
      out.write("         <a href=\"/FoodTrip/member/login\">로그인</a>\r\n");
      out.write("         <a href=\"/FoodTrip/member/email\">회원가입</a>\r\n");
      out.write("      ");
} 
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("	<div class=\"container\">	\r\n");
      out.write("		<div class=\"map_wrap\">\r\n");
      out.write("		    <div id=\"map\" style=\"width:100%;height:100%;position:relative;overflow:hidden;\"></div>\r\n");
      out.write("		\r\n");
      out.write("		    <div id=\"menu_wrap\" class=\"bg_white\">\r\n");
      out.write("		        <div class=\"option\">\r\n");
      out.write("		            <div>\r\n");
      out.write("		                <form onsubmit=\"searchPlaces(); return false;\">\r\n");
      out.write("		                    키워드 : <input type=\"text\" id=\"keyword\" size=\"15\"> \r\n");
      out.write("		                    <button type=\"submit\">검색하기</button> \r\n");
      out.write("		                </form>\r\n");
      out.write("		            </div>\r\n");
      out.write("		        </div>\r\n");
      out.write("		        <hr>\r\n");
      out.write("		        <ul id=\"placesList\"></ul>\r\n");
      out.write("		        <div id=\"pagination\"></div>\r\n");
      out.write("		    </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<form onsubmit=\"return false;\">\r\n");
      out.write("				<p>\r\n");
      out.write("					<label>마커ID</label>\r\n");
      out.write("					<input id=\"markerId\"/>\r\n");
      out.write("				</p>\r\n");
      out.write("				<p>\r\n");
      out.write("					<label>좌표 X</label>\r\n");
      out.write("					<input id=\"pointX\"/>\r\n");
      out.write("				<p>\r\n");
      out.write("					<label>좌표 Y</label>\r\n");
      out.write("					<input id=\"pointY\"/>\r\n");
      out.write("				<p>\r\n");
      out.write("					<label>카테고리</label>\r\n");
      out.write("					<input id=\"category\"/>\r\n");
      out.write("				<p>\r\n");
      out.write("					<label>장소명</label>\r\n");
      out.write("					<input id=\"pointName\"/>\r\n");
      out.write("				<p>\r\n");
      out.write("					<label>전화번호</label>\r\n");
      out.write("					<input id=\"phone\"/>\r\n");
      out.write("				<p>\r\n");
      out.write("					<label>주소</label>\r\n");
      out.write("					<input id=\"address\"/>\r\n");
      out.write("				<p>\r\n");
      out.write("					<label>정보보기</label>\r\n");
      out.write("					<a href=\"#\" id=\"urlData\" target=\"_blank\">정보보기</a>\r\n");
      out.write("				<p>\r\n");
      out.write("					<label>장소설명</label>\r\n");
      out.write("					<textarea id=\"description\" col=\"50\" row=\"20\"></textarea>\r\n");
      out.write("				<p>\r\n");
      out.write("					<label>장소이미지</label>\r\n");
      out.write("					<input id=\"image\" type=\"file\"/>\r\n");
      out.write("				\r\n");
      out.write("				<button id=\"sendData\">전송</button>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=a8fb3e9990ea2c741f7c154e957f99be&libraries=services\"></script>\r\n");
      out.write("	<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("	// input 태그 \r\n");
      out.write("	var id = document.querySelector(\"#markerId\");\r\n");
      out.write("	var px = document.querySelector(\"#pointX\");\r\n");
      out.write("	var py = document.querySelector(\"#pointY\");\r\n");
      out.write("	var cate = document.querySelector(\"#category\");\r\n");
      out.write("	var pn = document.querySelector(\"#pointName\");\r\n");
      out.write("	var ph = document.querySelector(\"#phone\");\r\n");
      out.write("	var addr = document.querySelector(\"#address\");\r\n");
      out.write("	var urldata = document.querySelector(\"#urlData\");\r\n");
      out.write("	var desc = document.querySelector(\"#description\");\r\n");
      out.write("	var send = document.querySelector(\"#sendData\");\r\n");
      out.write("	var insertKeyword = document.querySelector(\"#keyword\");\r\n");
      out.write("	var saveKeyword;\r\n");
      out.write("	var overlays = [];\r\n");
      out.write("	var overlay;\r\n");
      out.write("	var overlay_num;\r\n");
      out.write("	// 마커를 담을 배열입니다\r\n");
      out.write("	var markers = [];\r\n");
      out.write("	//dto 매핑 객체\r\n");
      out.write("	var dtoObjAry = [];\r\n");
      out.write("	var dtoObj ={\r\n");
      out.write("			//\"inputdata\":\"\",\r\n");
      out.write("			\"markerId\":\"\",\r\n");
      out.write("			\"pointX\":\"\",\r\n");
      out.write("			\"pointY\":\"\",\r\n");
      out.write("			\"category\":\"\",\r\n");
      out.write("			\"pointName\":\"\",\r\n");
      out.write("			\"phone\":\"\",\r\n");
      out.write("			\"address\":\"\",\r\n");
      out.write("			\"description\":\"\"\r\n");
      out.write("	};\r\n");
      out.write("	\r\n");
      out.write("	var mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("	    mapOption = {\r\n");
      out.write("	        center: new kakao.maps.LatLng(35.2538433, 128.6402609), // 지도의 중심좌표\r\n");
      out.write("	        level: 3 // 지도의 확대 레벨\r\n");
      out.write("	    };  \r\n");
      out.write("\r\n");
      out.write("	// 지도를 생성합니다    \r\n");
      out.write("	var map = new kakao.maps.Map(mapContainer, mapOption); \r\n");
      out.write("\r\n");
      out.write("	// 장소 검색 객체를 생성합니다\r\n");
      out.write("	var ps = new kakao.maps.services.Places();  \r\n");
      out.write("\r\n");
      out.write("	// 검색 결과 목록이나 마커를 클릭했을 때 장소명을 표출할 인포윈도우를 생성합니다\r\n");
      out.write("	var infowindow = new kakao.maps.InfoWindow({zIndex:1});\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	//이벤트 할당\r\n");
      out.write("	send.addEventListener('click', sendAllData);\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	//setInsertKey();\r\n");
      out.write("	// 키워드로 장소를 검색합니다\r\n");
      out.write("	searchPlaces();\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	// 키워드 검색을 요청하는 함수입니다\r\n");
      out.write("	function searchPlaces() {\r\n");
      out.write("		\r\n");
      out.write("	    var keyword = insertKeyword.value;\r\n");
      out.write("	    \r\n");
      out.write("	    if (!keyword.replace(/^\\s+|\\s+$/g, '')) {\r\n");
      out.write("	    //    alert('키워드를 입력해주세요!');\r\n");
      out.write("	        return false;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    //dtoObj.inputdata = keyword;\r\n");
      out.write("	    // 장소검색 객체를 통해 키워드로 장소검색을 요청합니다\r\n");
      out.write("	    ps.keywordSearch( keyword, placesSearchCB); \r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	// 장소검색이 완료됐을 때 호출되는 콜백함수 입니다\r\n");
      out.write("	/*\r\n");
      out.write("			여기서 마커들의 배열을 받아온다.\r\n");
      out.write("	*/	\r\n");
      out.write("	function placesSearchCB(data, status, pagination) {\r\n");
      out.write("	    if (status === kakao.maps.services.Status.OK) {\r\n");
      out.write("\r\n");
      out.write("	        // 정상적으로 검색이 완료됐으면\r\n");
      out.write("	        // 검색 목록과 마커를 표출합니다\r\n");
      out.write("	        displayPlaces(data);\r\n");
      out.write("\r\n");
      out.write("	        // 페이지 번호를 표출합니다\r\n");
      out.write("	        displayPagination(pagination);\r\n");
      out.write("\r\n");
      out.write("	    } else if (status === kakao.maps.services.Status.ZERO_RESULT) {\r\n");
      out.write("\r\n");
      out.write("	        alert('검색 결과가 존재하지 않습니다.');\r\n");
      out.write("	        return;\r\n");
      out.write("\r\n");
      out.write("	    } else if (status === kakao.maps.services.Status.ERROR) {\r\n");
      out.write("\r\n");
      out.write("	        alert('검색 결과 중 오류가 발생했습니다.');\r\n");
      out.write("	        return;\r\n");
      out.write("\r\n");
      out.write("	    }\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	// 검색 결과 목록과 마커를 표출하는 함수입니다\r\n");
      out.write("	function displayPlaces(places) {\r\n");
      out.write("\r\n");
      out.write("	    var listEl = document.getElementById('placesList'), \r\n");
      out.write("	    menuEl = document.getElementById('menu_wrap'),\r\n");
      out.write("	    fragment = document.createDocumentFragment(), \r\n");
      out.write("	    bounds = new kakao.maps.LatLngBounds(), \r\n");
      out.write("	    listStr = '';\r\n");
      out.write("	    \r\n");
      out.write("	    // 검색 결과 목록에 추가된 항목들을 제거합니다\r\n");
      out.write("	    removeAllChildNods(listEl);\r\n");
      out.write("\r\n");
      out.write("	    // 지도에 표시되고 있는 마커를 제거합니다\r\n");
      out.write("	    removeMarker();\r\n");
      out.write("	    \r\n");
      out.write("	    for ( var i=0; i<places.length; i++ ) {\r\n");
      out.write("	    	\r\n");
      out.write("	        // 마커를 생성하고 지도에 표시합니다\r\n");
      out.write("	        var placePosition = new kakao.maps.LatLng(places[i].y, places[i].x);\r\n");
      out.write("//	            marker = addMarker(placePosition, i),\r\n");
      out.write("			//마커 생성 --- (원본)함수구현\r\n");
      out.write("			var imageSrc = 'https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_number_blue.png', // 마커 이미지 url, 스프라이트 이미지를 씁니다\r\n");
      out.write("		        imageSize = new kakao.maps.Size(36, 37),  // 마커 이미지의 크기\r\n");
      out.write("		        imgOptions =  {\r\n");
      out.write("		            spriteSize : new kakao.maps.Size(36, 691), // 스프라이트 이미지의 크기\r\n");
      out.write("		            spriteOrigin : new kakao.maps.Point(0, (i*46)+10), // 스프라이트 이미지 중 사용할 영역의 좌상단 좌표\r\n");
      out.write("		            offset: new kakao.maps.Point(13, 37) // 마커 좌표에 일치시킬 이미지 내에서의 좌표\r\n");
      out.write("		        },\r\n");
      out.write("		        markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize, imgOptions),\r\n");
      out.write("		            marker = new kakao.maps.Marker({\r\n");
      out.write("		            position: placePosition, // 마커의 위치\r\n");
      out.write("		            image: markerImage \r\n");
      out.write("		        });\r\n");
      out.write("	\r\n");
      out.write("			    marker.setMap(map); // 지도 위에 마커를 표출합니다\r\n");
      out.write("			    markers.push(marker);  // 배열에 생성된 마커를 추가합니다\r\n");
      out.write("\r\n");
      out.write("	            itemEl = getListItem(i, places[i]); // 검색 결과 항목 Element를 생성합니다\r\n");
      out.write("     			\r\n");
      out.write("	            //********************  함수 삽입 ********************\r\n");
      out.write("	            // 마커 클릭 시, 위치 정보가 input태그에 바로 삽입될 수 있게하는 함수\r\n");
      out.write("	            setInputValue(marker, places[i]);\r\n");
      out.write("				\r\n");
      out.write("	            setEventList(itemEl, places[i]);\r\n");
      out.write("\r\n");
      out.write("	            \r\n");
      out.write("	        // 검색된 장소 위치를 기준으로 지도 범위를 재설정하기위해\r\n");
      out.write("	        // LatLngBounds 객체에 좌표를 추가합니다\r\n");
      out.write("	        bounds.extend(placePosition);\r\n");
      out.write("	        \r\n");
      out.write("	        // 마커와 검색결과 항목에 mouseover 했을때\r\n");
      out.write("	        // 해당 장소에 인포윈도우에 장소명을 표시합니다\r\n");
      out.write("	        // mouseout 했을 때는 인포윈도우를 닫습니다\r\n");
      out.write("	        (function(marker, data) {\r\n");
      out.write("	        	overlay_num = overlays.length;\r\n");
      out.write("				setDTO(data);\r\n");
      out.write("				//console.log(data);\r\n");
      out.write("	            kakao.maps.event.addListener(marker, 'click', function() {\r\n");
      out.write("	            	var content = '<div class=\"wrap\">' + \r\n");
      out.write("	            	'    <div class=\"info\">' + \r\n");
      out.write("	                '        <div class=\"title\">' + \r\n");
      out.write("	                '            '+ data.place_name + \r\n");
      out.write("	                '            <div class=\"close\" onclick=\"closeOverlay('+overlay_num+')\" title=\"닫기\"></div>' + \r\n");
      out.write("	                '        </div>' + \r\n");
      out.write("	                '        <div class=\"body\">' + \r\n");
      out.write("	                '            <div class=\"img\">' +\r\n");
      out.write("	                '                <img src=\"https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/thumnail.png\" width=\"73\" height=\"70\">' +\r\n");
      out.write("	                '           </div>' + \r\n");
      out.write("	                '            <div class=\"desc\">' + \r\n");
      out.write("	                '                <div class=\"ellipsis\">'+ data.road_address_name +'</div>' +  \r\n");
      out.write("	                '                <div><a href='+ data.place_url  +' target=\"_blank\" class=\"link\">사이트이동</a></div>' + \r\n");
      out.write("	                '            </div>' + \r\n");
      out.write("	                '        </div>' + \r\n");
      out.write("	                '    </div>' +    \r\n");
      out.write("	                '</div>';	            	\r\n");
      out.write("	            	\r\n");
      out.write("	            	overlay = new kakao.maps.CustomOverlay({\r\n");
      out.write("	            	    content: content,\r\n");
      out.write("	            	   // map: map,\r\n");
      out.write("	            	    position: marker.getPosition()       \r\n");
      out.write("	            	});\r\n");
      out.write("	            	overlays.push(overlay);\r\n");
      out.write("	            	overlay.setMap(map);\r\n");
      out.write("	            });\r\n");
      out.write("/*\r\n");
      out.write("	            kakao.maps.event.addListener(marker, 'mouseout', function() {\r\n");
      out.write("	                infowindow.close();\r\n");
      out.write("	            });\r\n");
      out.write("\r\n");
      out.write("	            itemEl.onmouseover =  function () {\r\n");
      out.write("	                displayInfowindow(marker, title);\r\n");
      out.write("	            };\r\n");
      out.write("\r\n");
      out.write("	            itemEl.onmouseout =  function () {\r\n");
      out.write("	                infowindow.close();\r\n");
      out.write("	            };*/\r\n");
      out.write("	        })(marker, places[i]);\r\n");
      out.write("	        \r\n");
      out.write("	        \r\n");
      out.write("	        fragment.appendChild(itemEl);\r\n");
      out.write("	    }\r\n");
      out.write("		\r\n");
      out.write("	    // 검색결과 항목들을 검색결과 목록 Element에 추가합니다\r\n");
      out.write("	    listEl.appendChild(fragment);\r\n");
      out.write("	    menuEl.scrollTop = 0;\r\n");
      out.write("\r\n");
      out.write("	    // 검색된 장소 위치를 기준으로 지도 범위를 재설정합니다\r\n");
      out.write("	    map.setBounds(bounds);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function closeOverlay(num) {\r\n");
      out.write("	    overlays[num].setMap(null);     \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	// 검색결과 항목을 Element로 반환하는 함수입니다\r\n");
      out.write("	function getListItem(index, places) {\r\n");
      out.write("\r\n");
      out.write("	    var el = document.createElement('li'),\r\n");
      out.write("	    itemStr = '<span class=\"markerbg marker_' + (index+1) + '\"></span>' +\r\n");
      out.write("	                '<div class=\"info\">' +\r\n");
      out.write("	                '   <h5>' + places.place_name + '</h5>';\r\n");
      out.write("\r\n");
      out.write("	    if (places.road_address_name) {\r\n");
      out.write("	        itemStr += '    <span>' + places.road_address_name + '</span>' +\r\n");
      out.write("	                    '   <span class=\"jibun gray\">' +  places.address_name  + '</span>';\r\n");
      out.write("	    } else {\r\n");
      out.write("	        itemStr += '    <span>' +  places.address_name  + '</span>'; \r\n");
      out.write("	    }\r\n");
      out.write("	                 \r\n");
      out.write("	      itemStr += '  <span class=\"tel\">' + places.phone  + '</span>' +\r\n");
      out.write("	                '</div>';           \r\n");
      out.write("\r\n");
      out.write("	    el.innerHTML = itemStr;\r\n");
      out.write("	    el.className = 'item';\r\n");
      out.write("\r\n");
      out.write("	    return el;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	// 마커를 생성하고 지도 위에 마커를 표시하는 함수입니다\r\n");
      out.write("	// 원래 함수로 사용하고 있었으나 현재는 밖으로 꺼내 사용하지 않고 있음\r\n");
      out.write("/*	\r\n");
      out.write("	function addMarker(position, idx, title) {\r\n");
      out.write("	    var imageSrc = 'https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_number_blue.png', // 마커 이미지 url, 스프라이트 이미지를 씁니다\r\n");
      out.write("	        imageSize = new kakao.maps.Size(36, 37),  // 마커 이미지의 크기\r\n");
      out.write("	        imgOptions =  {\r\n");
      out.write("	            spriteSize : new kakao.maps.Size(36, 691), // 스프라이트 이미지의 크기\r\n");
      out.write("	            spriteOrigin : new kakao.maps.Point(0, (idx*46)+10), // 스프라이트 이미지 중 사용할 영역의 좌상단 좌표\r\n");
      out.write("	            offset: new kakao.maps.Point(13, 37) // 마커 좌표에 일치시킬 이미지 내에서의 좌표\r\n");
      out.write("	        },\r\n");
      out.write("	        markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize, imgOptions),\r\n");
      out.write("	            marker = new kakao.maps.Marker({\r\n");
      out.write("	            position: position, // 마커의 위치\r\n");
      out.write("	            image: markerImage \r\n");
      out.write("	        });\r\n");
      out.write("\r\n");
      out.write("	    marker.setMap(map); // 지도 위에 마커를 표출합니다\r\n");
      out.write("	    markers.push(marker);  // 배열에 생성된 마커를 추가합니다\r\n");
      out.write("\r\n");
      out.write("	    return marker;\r\n");
      out.write("	}\r\n");
      out.write("*/\r\n");
      out.write("	// 지도 위에 표시되고 있는 마커를 모두 제거합니다\r\n");
      out.write("	function removeMarker() {\r\n");
      out.write("	    for ( var i = 0; i < markers.length; i++ ) {\r\n");
      out.write("	        markers[i].setMap(null);\r\n");
      out.write("	    }   \r\n");
      out.write("	    markers = [];\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	// 검색결과 목록 하단에 페이지번호를 표시는 함수입니다\r\n");
      out.write("	function displayPagination(pagination) {\r\n");
      out.write("	    var paginationEl = document.getElementById('pagination'),\r\n");
      out.write("	        fragment = document.createDocumentFragment(),\r\n");
      out.write("	        i; \r\n");
      out.write("\r\n");
      out.write("	    // 기존에 추가된 페이지번호를 삭제합니다\r\n");
      out.write("	    while (paginationEl.hasChildNodes()) {\r\n");
      out.write("	        paginationEl.removeChild (paginationEl.lastChild);\r\n");
      out.write("	    }\r\n");
      out.write("\r\n");
      out.write("	    for (i=1; i<=pagination.last; i++) {\r\n");
      out.write("	        var el = document.createElement('a');\r\n");
      out.write("	        el.href = \"#\";\r\n");
      out.write("	        el.innerHTML = i;\r\n");
      out.write("\r\n");
      out.write("	        if (i===pagination.current) {\r\n");
      out.write("	            el.className = 'on';\r\n");
      out.write("	        } else {\r\n");
      out.write("	            el.onclick = (function(i) {\r\n");
      out.write("	                return function() {\r\n");
      out.write("	                    pagination.gotoPage(i);\r\n");
      out.write("	                }\r\n");
      out.write("	            })(i);\r\n");
      out.write("	        }\r\n");
      out.write("\r\n");
      out.write("	        fragment.appendChild(el);\r\n");
      out.write("	    }\r\n");
      out.write("	    paginationEl.appendChild(fragment);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	// 검색결과 목록 또는 마커를 클릭했을 때 호출되는 함수입니다\r\n");
      out.write("	// 인포윈도우에 장소명을 표시합니다\r\n");
      out.write("	function displayInfowindow(marker, title) {\r\n");
      out.write("	    var content = '<div style=\"padding:5px;z-index:1;\">' + title + '</div>';\r\n");
      out.write("\r\n");
      out.write("	    infowindow.setContent(content);\r\n");
      out.write("	    infowindow.open(map, marker);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	 // 검색결과 목록의 자식 Element를 제거하는 함수입니다\r\n");
      out.write("	function removeAllChildNods(el) {   \r\n");
      out.write("	    while (el.hasChildNodes()) {\r\n");
      out.write("	        el.removeChild (el.lastChild);\r\n");
      out.write("	    }\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function setEventList(list, data){\r\n");
      out.write("		list.onclick = function(){\r\n");
      out.write("	        pn.value = data.place_name;\r\n");
      out.write("	    	px.value = data.x;\r\n");
      out.write("	    	py.value = data.y;\r\n");
      out.write("	    	addr.value = data.address_name;\r\n");
      out.write("	    	ph.value = data.phone;\r\n");
      out.write("	    	cate.value = data.category_name;\r\n");
      out.write("	    	urldata.href = data.place_url;\r\n");
      out.write("	    	setDTO(data);\r\n");
      out.write("	     };\r\n");
      out.write("	}\r\n");
      out.write("	 \r\n");
      out.write("	function setInputValue(marker, data){\r\n");
      out.write("		/*\r\n");
      out.write("		Document data \r\n");
      out.write("			이름					타입			설명\r\n");
      out.write("			id					String		장소 ID\r\n");
      out.write("			place_name			String		장소명, 업체명\r\n");
      out.write("			category_name		String		카테고리 이름\r\n");
      out.write("			category_group_code	String		중요 카테고리만 그룹핑한 카테고리 그룹 코드\r\n");
      out.write("			category_group_name	String		중요 카테고리만 그룹핑한 카테고리 그룹명\r\n");
      out.write("			phone				String		전화번호\r\n");
      out.write("			address_name		String		전체 지번 주소\r\n");
      out.write("			road_address_name	String		전체 도로명 주소\r\n");
      out.write("			x					String		X 좌표값, 경위도인 경우 longitude (경도)\r\n");
      out.write("			y					String		Y 좌표값, 경위도인 경우 latitude(위도)\r\n");
      out.write("			place_url			String		장소 상세페이지 URL\r\n");
      out.write("			distance			String		중심좌표까지의 거리 (단, x,y 파라미터를 준 경우에만 존재)\r\n");
      out.write("			단위 meter\r\n");
      out.write("		*/	\r\n");
      out.write("		kakao.maps.event.addListener(marker,'click', function(){\r\n");
      out.write("			//id.value = data.id;\r\n");
      out.write("			pn.value = data.place_name;\r\n");
      out.write("			px.value = data.x;\r\n");
      out.write("			py.value = data.y;\r\n");
      out.write("			addr.value = data.address_name;\r\n");
      out.write("			ph.value = data.phone;\r\n");
      out.write("			cate.value = data.category_name;\r\n");
      out.write("			urldata.href = data.place_url;\r\n");
      out.write("			desc.value = data.place_url;\r\n");
      out.write("			//setDTO(data);\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function setDTO(data){\r\n");
      out.write("		var dtoObj = {};\r\n");
      out.write("		//dtoObj.markerId:data.place_name,\r\n");
      out.write("		dtoObj.pointX = data.x;\r\n");
      out.write("		dtoObj.pointY = data.y;\r\n");
      out.write("		dtoObj.category = data.category_name;\r\n");
      out.write("		dtoObj.pointName = data.place_name;\r\n");
      out.write("		dtoObj.phone = data.phone;\r\n");
      out.write("		dtoObj.address = data.address_name;\r\n");
      out.write("		dtoObj.description = data.place_url;\r\n");
      out.write("		dtoObjAry.push(dtoObj);\r\n");
      out.write("		//console.log(dtoObjAry);\r\n");
      out.write("		console.log(dtoObjAry.length);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function sendAllData(){\r\n");
      out.write("		console.log(dtoObjAry.length);\r\n");
      out.write("		for(var i=0; i<dtoObjAry.length; i++){\r\n");
      out.write("        	//setDTO(data);\r\n");
      out.write("        	sendData(dtoObjAry[i]);\r\n");
      out.write("		}\r\n");
      out.write("		dtoObjAry=[];\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function sendData(dtoOne){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : \"/FoodTrip/marker/addMarker\",\r\n");
      out.write("			type : \"post\",\r\n");
      out.write("			async : false,\r\n");
      out.write("			data : JSON.stringify(dtoOne),\r\n");
      out.write("			contentType : \"application/json\",\r\n");
      out.write("			success : function(response){\r\n");
      out.write("				if(response){\r\n");
      out.write("					//alert(\"마커가 정상적으로 입력되었습니다.\");   //현재 배열 요소를 한번씩 보내고 있어서 일부러 중지\r\n");
      out.write("				}else{\r\n");
      out.write("					alert(\"마커 데이터가 이미 존재합니다.\");\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			error : function(){\r\n");
      out.write("				alert(\"마커 입력 에러\")\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function setInsertKey(){\r\n");
      out.write("		insertKeyword.value = saveKeyword;\r\n");
      out.write("	}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
