/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2024-12-18 05:57:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.marker;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.spring.domain.*;
import java.util.*;
import com.spring.domain.Member;

public final class markerListJS_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/menu/menu.jsp", Long.valueOf(1734490594000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.spring.domain");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.spring.domain.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/FoodTrip/resources/css/menu.css\"/>\r\n");
      out.write("<style>\r\n");
      out.write("	.contain{\r\n");
      out.write("		display:flex;\r\n");
      out.write("	}\r\n");
      out.write("	.listBox{\r\n");
      out.write("		width:250px;\r\n");
      out.write("		height:800px;\r\n");
      out.write("		position: relative;\r\n");
      out.write("		overflow:hidden;\r\n");
      out.write("		background-color: #EFF2FB;\r\n");
      out.write("		border:1px solid black;\r\n");
      out.write("	}\r\n");
      out.write("	.listBox > *, ul{\r\n");
      out.write("		padding:0;\r\n");
      out.write("		margin:0 auto;\r\n");
      out.write("	}\r\n");
      out.write("	.listbody{\r\n");
      out.write("		height:100%;\r\n");
      out.write("		position:relative;\r\n");
      out.write("		overflow-y:auto;\r\n");
      out.write("	}\r\n");
      out.write("	.tablist{\r\n");
      out.write("		list-style:none;\r\n");
      out.write("		display:flex;\r\n");
      out.write("		justify-content:space-between;\r\n");
      out.write("	}\r\n");
      out.write("	.tablist button{\r\n");
      out.write("		width:100%;\r\n");
      out.write("	}\r\n");
      out.write("	.tablist div{\r\n");
      out.write("		width:30%;\r\n");
      out.write("		margin:0 10px 0 10px;\r\n");
      out.write("		border:1px solid rgba(0,0,0,0.3);\r\n");
      out.write("	}\r\n");
      out.write("	.markerList{\r\n");
      out.write("		display:flex;\r\n");
      out.write("		flex-direction:column;\r\n");
      out.write("		list-style : none;\r\n");
      out.write("	}\r\n");
      out.write("	.listCh{\r\n");
      out.write("		width:80%;\r\n");
      out.write("		margin-top: 10px;\r\n");
      out.write("		margin-left: 20px;\r\n");
      out.write("		margin-bottom: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	.listblock{\r\n");
      out.write("		position:absolute;\r\n");
      out.write("		top:0;\r\n");
      out.write("		left:0;\r\n");
      out.write("	}\r\n");
      out.write("	div ul{\r\n");
      out.write("		list-style:none;\r\n");
      out.write("	}\r\n");
      out.write("	.btnList{\r\n");
      out.write("		display:flex;\r\n");
      out.write("		justify-content:space-between;\r\n");
      out.write("	}\r\n");
      out.write("	.btnList a{\r\n");
      out.write("		color:rgb(2,7,21);\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		text-decoration:none;\r\n");
      out.write("		background-color:#E6E6E6;\r\n");
      out.write("		padding:3px;\r\n");
      out.write("		border-radius:10px;\r\n");
      out.write("	}\r\n");
      out.write("	.pointName{\r\n");
      out.write("		font-weight:700;\r\n");
      out.write("		text-decoration:none;\r\n");
      out.write("		color:black;\r\n");
      out.write("	}\r\n");
      out.write("	.category{\r\n");
      out.write("		font-size:11px;\r\n");
      out.write("	}\r\n");
      out.write("	.wrap {position: absolute;left: 0;bottom: 40px;width: 288px;height: 132px;margin-left: -144px;text-align: left;overflow: hidden;font-size: 12px;font-family: 'Malgun Gothic', dotum, '돋움', sans-serif;line-height: 1.5;}\r\n");
      out.write("    .wrap * {padding: 0;margin: 0;}\r\n");
      out.write("    .wrap .info {width: 286px;height: 120px;border-radius: 5px;border-bottom: 2px solid #ccc;border-right: 1px solid #ccc;overflow: hidden;background: #fff;}\r\n");
      out.write("    .wrap .info:nth-child(1) {border: 0;box-shadow: 0px 1px 2px #888;}\r\n");
      out.write("    .info .title {padding: 5px 0 0 10px;height: 30px;background: #eee;border-bottom: 1px solid #ddd;font-size: 18px;font-weight: bold;}\r\n");
      out.write("    .info .close {position: absolute;top: 10px;right: 10px;color: #888;width: 17px;height: 17px;background: url('https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/overlay_close.png');}\r\n");
      out.write("    .info .close:hover {cursor: pointer;}\r\n");
      out.write("    .info .body {position: relative;overflow: hidden;}\r\n");
      out.write("    .info .desc {position: relative;margin: 13px 0 0 90px;height: 75px;}\r\n");
      out.write("    .desc .ellipsis {overflow: hidden;text-overflow: ellipsis;white-space: nowrap;}\r\n");
      out.write("    .desc .jibun {font-size: 11px;color: #888;margin-top: -2px;}\r\n");
      out.write("    .info .img {position: absolute;top: 6px;left: 5px;width: 73px;height: 71px;border: 1px solid #ddd;color: #888;overflow: hidden;}\r\n");
      out.write("    .info:after {content: '';position: absolute;margin-left: -12px;left: 50%;bottom: 0;width: 22px;height: 12px;background: url('https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/vertex_white.png')}\r\n");
      out.write("    .info .link {color: #5085BB;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   HttpSession session = request.getSession(false);
   Member sessionId = null;
   String adminCheck = null;
   if(session != null){
      sessionId = (Member)session.getAttribute("sessionId");
      adminCheck = (String)sessionId.getNickName();
      System.out.println("게시글 작성 폼 세션 널아님!!");
      System.out.println("닉네임 : " + sessionId.getNickName());
      System.out.println("참거짓 : " + sessionId != null);
      System.out.println("참거짓 : " + adminCheck.equals("admin"));
   }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"display:flex\">\r\n");
   if(sessionId != null && adminCheck.equals("admin")){ 
      out.write("\r\n");
      out.write("   <div id=\"menublock\">\r\n");
      out.write("      <a href=\"/FoodTrip/marker/test\">마커 생성</a>\r\n");
      out.write("      <a href=\"/FoodTrip/marker/readalljson\">마커 전체 가져오기</a>\r\n");
      out.write("      <a href=\"/FoodTrip/road/makeRoad\">코스 생성</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");
} 
      out.write("\r\n");
      out.write("   <div id=\"menublock\">\r\n");
      out.write("      <a href=\"/FoodTrip/road/readRoad\">코스 전체보기</a>\r\n");
      out.write("      <a href=\"/FoodTrip/board/boards\">리뷰게시판</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div id=\"menublock\">\r\n");
      out.write("      ");

      if(sessionId != null && sessionId.getNickName() != null && !sessionId.getNickName().isEmpty()){
      
      out.write("\r\n");
      out.write("         <a href=\"/FoodTrip/member/logout\">로그아웃</a>\r\n");
      out.write("         <a href=\"/FoodTrip/member/update\">회원정보수정</a>\r\n");
      out.write("      ");
}else{
      out.write("\r\n");
      out.write("         <a href=\"/FoodTrip/member/login\">로그인</a>\r\n");
      out.write("         <a href=\"/FoodTrip/member/email\">회원가입</a>\r\n");
      out.write("      ");
} 
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("	<!-- \r\n");
      out.write("		<ul>\r\n");
      out.write("			<li>로 구현할 때 \r\n");
      out.write("			전체 리스트로 쭉 뿌리고 카테고리에 따라 분류	\r\n");
      out.write("	 -->\r\n");
      out.write("	<h2>마커 리스트</h2>\r\n");
      out.write("<div class=\"contain\">\r\n");
      out.write("<!-- 	\r\n");
      out.write("	<div class=\"listBox\">\r\n");
      out.write("		<ul class=\"tablist\">\r\n");
      out.write("			<div class=\"tourtab\" id=\"tab\">관광지</div>\r\n");
      out.write("			<div class=\"resttab\" id=\"tab\">식당</div>\r\n");
      out.write("			<div class=\"staytab\" id=\"tab\">숙소</div>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<ul class=\"markerList\">\r\n");
      out.write("		\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	 -->\r\n");
      out.write("	<div class=\"listBox\">\r\n");
      out.write("		<div class=\"tablist\">\r\n");
      out.write("			<button class=\"tourtab\" id=\"TU\">관광지</button>\r\n");
      out.write("			<button class=\"resttab\" id=\"RS\">식당</button>\r\n");
      out.write("			<button class=\"staytab\" id=\"HT\">숙소</button>\r\n");
      out.write("		</div>	\r\n");
      out.write("		<div class=\"listbody\">\r\n");
      out.write("			<div class=\"listblock\">\r\n");
      out.write("				<ul class=\"mklist\">\r\n");
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=map style=\"width:100%;height:800px;\">\r\n");
      out.write("		<!-- 지도 공간  -->\r\n");
      out.write("		\r\n");
      out.write("	</div> \r\n");
      out.write("</div>		\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=a8fb3e9990ea2c741f7c154e957f99be\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	//맵 변수\r\n");
      out.write("	var mapContainer;\r\n");
      out.write("	var map;\r\n");
      out.write("	//리스트 li를 추가할 부모요소\r\n");
      out.write("	var mkParents = document.querySelector(\".mklist\");\r\n");
      out.write("	\r\n");
      out.write("	//리스트 탭\r\n");
      out.write("	var tourTab = document.querySelector(\".tourtab\");\r\n");
      out.write("	var restTab = document.querySelector(\".resttab\");\r\n");
      out.write("	var stayTab = document.querySelector(\".staytab\");\r\n");
      out.write("	\r\n");
      out.write("	//이벤트 타겟\r\n");
      out.write("	//var whoTarget;\r\n");
      out.write("	\r\n");
      out.write("	//원 반경을 표시하는 변수\r\n");
      out.write("	let activeCircle = null;\r\n");
      out.write("	\r\n");
      out.write("	//마커가 맵에 표시될 때 저장되는 마커 배열\r\n");
      out.write("	var baseMarkers = [];\r\n");
      out.write("	\r\n");
      out.write("	//반경 내 마커만 저장하는 배열\r\n");
      out.write("	var circleMarkers = [];\r\n");
      out.write("	\r\n");
      out.write("	//DB에서 가져온 마커 DTO Ary\r\n");
      out.write("	var dtoList=[];\r\n");
      out.write("	\r\n");
      out.write("	//오버레이 이벤트 사용변수\r\n");
      out.write("	var overlay;\r\n");
      out.write("	var overlayAry= [];\r\n");
      out.write("	\r\n");
      out.write("	//마커 DTO\r\n");
      out.write("	var dtoObj = {\r\n");
      out.write("		\"inputdata\":\"\",\r\n");
      out.write("		\"markerId\":\"\",\r\n");
      out.write("		\"pointX\":\"\",\r\n");
      out.write("		\"pointY\":\"\",\r\n");
      out.write("		\"category\":\"\",\r\n");
      out.write("		\"pointName\":\"\",\r\n");
      out.write("		\"phone\":\"\",\r\n");
      out.write("		\"address\":\"\",\r\n");
      out.write("		\"description\":\"\"\r\n");
      out.write("	};\r\n");
      out.write("\r\n");
      out.write("	//탭 버튼에 이벤트 할당\r\n");
      out.write("	tourTab.addEventListener(\"click\",() => listFilter(event, dtoList));\r\n");
      out.write("	restTab.addEventListener(\"click\",() => listFilter(event, dtoList));\r\n");
      out.write("	stayTab.addEventListener(\"click\",() => listFilter(event, dtoList));\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	//가장 먼저 실행되는 ajax\r\n");
      out.write("	getAllMarker();	\r\n");
      out.write("	makeMap();\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	//데이터 가져오기\r\n");
      out.write("	function getAllMarker(){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : \"readMkAll\",\r\n");
      out.write("			type : \"get\",\r\n");
      out.write("			success: function(response) {\r\n");
      out.write("		        //console.log(response);  // 응답 구조를 확인\r\n");
      out.write("				JSON.stringify(response);\r\n");
      out.write("		        // 응답이 배열인지 확인하고, 배열이 비어있지 않으면\r\n");
      out.write("		        if (Array.isArray(response) && response.length > 0) {\r\n");
      out.write("		        	mkParents.innerHTML = \"\";\r\n");
      out.write("		        	copyMk(response);	//가져온 응답을 dto로 만들어 ary에 저장\r\n");
      out.write("		        } else {\r\n");
      out.write("		            console.log(\"응답이 비어있거나 배열이 아닙니다.\");\r\n");
      out.write("		        }\r\n");
      out.write("		    },\r\n");
      out.write("		    error: function(status) {\r\n");
      out.write("		        console.log(\"상태:\", status);\r\n");
      out.write("		    }\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	function copyMk(markerlist){\r\n");
      out.write("		console.log(markerlist.length);\r\n");
      out.write("		for(var i=0; i<markerlist.length; i++){\r\n");
      out.write("			(function(index){\r\n");
      out.write("			//객체를 새로 생성하지 않으면 참조 오류가 생긴다.\r\n");
      out.write("			var dtoObj ={\r\n");
      out.write("				\"markerId\":markerlist[index].markerId,\r\n");
      out.write("				\"pointX\": markerlist[index].pointX,\r\n");
      out.write("			    \"pointY\": markerlist[index].pointY,\r\n");
      out.write("				\"category\":markerlist[index].category,\r\n");
      out.write("				\"pointName\":markerlist[index].pointName,\r\n");
      out.write("				\"phone\":markerlist[index].phone,\r\n");
      out.write("				\"address\": markerlist[index].address,\r\n");
      out.write("				\"description\":markerlist[index].description\r\n");
      out.write("			};\r\n");
      out.write("\r\n");
      out.write("			dtoList.push(dtoObj);\r\n");
      out.write("			})(i);\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	// 지도 출력을 위한 기본적인 코드 -------- START\r\n");
      out.write("	function makeMap(){\r\n");
      out.write("		mapContainer = document.getElementById('map'); // 지도를 표시할 div \r\n");
      out.write("	    var mapOption = { \r\n");
      out.write("	        center: new kakao.maps.LatLng(35.2538433, 128.6402609), // 지도의 중심좌표\r\n");
      out.write("	        level: 9 // 지도의 확대 레벨\r\n");
      out.write("	    };\r\n");
      out.write("\r\n");
      out.write("		map = new kakao.maps.Map(mapContainer, mapOption); \r\n");
      out.write("	}\r\n");
      out.write("	// 지도 출력을 위한 기본적인 코드 -------- END\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	//리스트 만들기\r\n");
      out.write("	function listMake(list, data){\r\n");
      out.write("		//console.log(data.description);\r\n");
      out.write("		list.innerHTML=\"<a href='\"+data.description+\"'class='pointName' target='_blank'>\"\r\n");
      out.write("		+ data.pointName + \"</a><div class='category'>\"+data.category\r\n");
      out.write("		+\"</div><br>\"\r\n");
      out.write("		//\r\n");
      out.write("		var div = document.createElement('div');\r\n");
      out.write("		div.setAttribute(\"class\", \"btnList\");\r\n");
      out.write("		div.innerHTML = \"<a href='/FoodTrip/marker/markerUpdate?id=\"+data.markerId+\"'>수정</a>\";\r\n");
      out.write("		\r\n");
      out.write("		var btn = document.createElement('button');\r\n");
      out.write("		var hr = document.createElement('hr');\r\n");
      out.write("		btn.addEventListener(\"click\", () => addMarker(data));\r\n");
      out.write("		btn.innerHTML = \"등록\";\r\n");
      out.write("		div.appendChild(btn);\r\n");
      out.write("		\r\n");
      out.write("		list.appendChild(div);\r\n");
      out.write("		list.appendChild(hr);\r\n");
      out.write("		//list.innerHTML += `</div>`;\r\n");
      out.write("	}//삭제 버튼 : <a href='/FoodTrip/marker/delete?id=\"+data.markerId+\"'>삭제</a></div><hr>\r\n");
      out.write("	\r\n");
      out.write("	//마커 찍기\r\n");
      out.write("	/*\r\n");
      out.write("		맵에 마커를 출력하며 마커에 이벤트를 할당하는 함수\r\n");
      out.write("		Param : cate(마커의 카테고리), data(마커 dto 리스트)\r\n");
      out.write("	*/\r\n");
      out.write("	function addMarkerInCircle(cate, img, data){\r\n");
      out.write("		//console.log(circleMarkers);\r\n");
      out.write("		var placePosition = new kakao.maps.LatLng(data.pointY, data.pointX);\r\n");
      out.write("		var imgfile;\r\n");
      out.write("		if(img==\"카페\"|| img==\"간식\"){\r\n");
      out.write("			imgfile = \"disert\";\r\n");
      out.write("		}else if(img==\"치킨\"){\r\n");
      out.write("			imgfile = \"chicken\";\r\n");
      out.write("		}else if(img==\"분식\"){\r\n");
      out.write("			imgfile = \"tteok\";\r\n");
      out.write("		}else{\r\n");
      out.write("			imgfile = cate;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		var imageSrc = \"/FoodTrip/resources/images/\"+imgfile+\".png\", // 마커 이미지 url, 스프라이트 이미지를 씁니다	\r\n");
      out.write("	        imageSize = new kakao.maps.Size(38, 38),  // 마커 이미지의 크기\r\n");
      out.write("	        imgOptions =  {	      \r\n");
      out.write("	            offset: new kakao.maps.Point(13, 37) // 마커 좌표에 일치시킬 이미지 내에서의 좌표\r\n");
      out.write("	        };\r\n");
      out.write("        console.log(\"imageSrc\");\r\n");
      out.write("		console.log(imageSrc);\r\n");
      out.write("		markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize, imgOptions),\r\n");
      out.write("	        marker = new kakao.maps.Marker({\r\n");
      out.write("	        map : map,\r\n");
      out.write("	        position: placePosition, // 마커의 위치\r\n");
      out.write("	        image: markerImage				            \r\n");
      out.write("	    });	\r\n");
      out.write("		\r\n");
      out.write("		createOverLay(marker, data);\r\n");
      out.write("		/*\r\n");
      out.write("		kakao.maps.event.addListener(marker, 'click', function () {\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("		*/\r\n");
      out.write("		 \r\n");
      out.write("		 return marker;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function addMarker(cate, data){\r\n");
      out.write("		console.log(cate);\r\n");
      out.write("		var placePosition = new kakao.maps.LatLng(data.pointY, data.pointX);\r\n");
      out.write("		bounds = new kakao.maps.LatLngBounds();\r\n");
      out.write("		bounds.extend(placePosition);\r\n");
      out.write("		var imageSrc = \"/FoodTrip/resources/images/\"+cate+\".png\" , // 마커 이미지 url, 스프라이트 이미지를 씁니다\r\n");
      out.write("	        imageSize = new kakao.maps.Size(36, 37),  // 마커 이미지의 크기\r\n");
      out.write("	        imgOptions =  {	      \r\n");
      out.write("	            offset: new kakao.maps.Point(13, 37) // 마커 좌표에 일치시킬 이미지 내에서의 좌표\r\n");
      out.write("	        };\r\n");
      out.write("		 \r\n");
      out.write("		 markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize, imgOptions),\r\n");
      out.write("	         marker = new kakao.maps.Marker({\r\n");
      out.write("	       	 map:map,\r\n");
      out.write("	         position: placePosition, // 마커의 위치\r\n");
      out.write("	         image: markerImage				            \r\n");
      out.write("	     });\r\n");
      out.write("\r\n");
      out.write("		 marker.setMap(map);\r\n");
      out.write("		 baseMarkers.push(marker);\r\n");
      out.write("\r\n");
      out.write("		clickListener(marker, data);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function clickListener(marker,data){\r\n");
      out.write("		kakao.maps.event.addListener(marker, 'click', function () {\r\n");
      out.write("	    	// 클릭된 마커를 중심으로 원을 그리도록 함수 호출\r\n");
      out.write("	    	getRangeRestTour(marker, data);\r\n");
      out.write("	    	//filterMarkersByCircle(oneMarker, data);\r\n");
      out.write("	    	console.log(\"1. click ! \");\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/*\r\n");
      out.write("		마커를 클릭했을 때 위도,경도로 계산된 반경 내 해당하는 마커만 출력\r\n");
      out.write("	*/\r\n");
      out.write("	function getRangeRestTour(marker, data){\r\n");
      out.write("		markersByCircle(marker, data);\r\n");
      out.write("		//console.log(data.pointX, data.pointY);\r\n");
      out.write("		//console.log(\"rm circle before\");\r\n");
      out.write("		console.log(\"3. range check\");\r\n");
      out.write("		rmAllMarker(circleMarkers);\r\n");
      out.write("		var exist = false;\r\n");
      out.write("		var x = data.pointX;\r\n");
      out.write("		var y = data.pointY;\r\n");
      out.write("		var positionX;\r\n");
      out.write("		var positionY;	\r\n");
      out.write("	//	console.log(\"test point\");\r\n");
      out.write("		//dtoList는 마커 전체 리스트\r\n");
      out.write("		for(var i=0; i<dtoList.length; i++){\r\n");
      out.write("			var cate = dtoList[i].markerId.substring(0,2);\r\n");
      out.write("			//카테고리 분할\r\n");
      out.write("			var cateFull = dtoList[i].category;\r\n");
      out.write("			var str1 = cateFull.replaceAll('>', ',');\r\n");
      out.write("			//var trimstr = str1.trim();\r\n");
      out.write("			var str2 = str1.split(',');\r\n");
      out.write("			var imgname = str2[1].trim();\r\n");
      out.write("			/*\r\n");
      out.write("			if(str2[1].trim()==\"카페\"){\r\n");
      out.write("				console.log(\"카페가 맞습니다.\");\r\n");
      out.write("			}\r\n");
      out.write("			*/\r\n");
      out.write("			//console.log(trimstr);\r\n");
      out.write("			\r\n");
      out.write("			var viewdata = dtoList[i];\r\n");
      out.write("			positionX = viewdata.pointX;\r\n");
      out.write("			positionY = viewdata.pointY;\r\n");
      out.write("			if(cate==\"RS\"){\r\n");
      out.write("				//위도 경도 조건 \r\n");
      out.write("				var km = haversineDistance(x, y, positionX, positionY);\r\n");
      out.write("				if(km <= 0.69){\r\n");
      out.write("				//	markersByCircle(marker, data, 0);\r\n");
      out.write("				//	console.log(\"km :  \"+km);\r\n");
      out.write("					var cMarker = addMarkerInCircle(cate, imgname ,viewdata);\r\n");
      out.write("					circleMarkers.push(cMarker);	\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function createOverLay(marker, data){\r\n");
      out.write("	   		overId = overlayAry.length;\r\n");
      out.write("	   		// console.log(overlayAry);\r\n");
      out.write("	   		console.log(\"overid : \"+overId);\r\n");
      out.write("	   		var content = '<div class=\"wrap\">' + \r\n");
      out.write("        	'    <div class=\"info\">' + \r\n");
      out.write("            '        <div class=\"title\">' + \r\n");
      out.write("            '            '+ data.pointName + \r\n");
      out.write("            '            <div class=\"close\" onclick=\"closeOverlay('+overId+')\" title=\"닫기\"></div>' + \r\n");
      out.write("            '        </div>' + \r\n");
      out.write("            '        <div class=\"body\">' + \r\n");
      out.write("            '            <div class=\"img\">' +\r\n");
      out.write("            '                <img src=\"https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/thumnail.png\" width=\"73\" height=\"70\">' +\r\n");
      out.write("            '           </div>' + \r\n");
      out.write("            '            <div class=\"desc\">' + \r\n");
      out.write("            '                <div class=\"ellipsis\">'+ data.address +'</div>' +  \r\n");
      out.write("            '                <div><a href='+ data.description  +' target=\"_blank\" class=\"link\">사이트이동</a></div>' + \r\n");
      out.write("            '            </div>' + \r\n");
      out.write("            '        </div>' + \r\n");
      out.write("            '    </div>' +    \r\n");
      out.write("            '</div>';	            	\r\n");
      out.write("        	//closeOverlay();\r\n");
      out.write("        	var overlay = new kakao.maps.CustomOverlay({\r\n");
      out.write("        	    content: content,\r\n");
      out.write("        	   // map: map,\r\n");
      out.write("        	    position: marker.getPosition()       \r\n");
      out.write("        	});\r\n");
      out.write("        	overlayAry.push(overlay);\r\n");
      out.write("        	\r\n");
      out.write("           	kakao.maps.event.addListener(marker, 'click', function() {\r\n");
      out.write("	            	overlay.setMap(map);\r\n");
      out.write("           	});\r\n");
      out.write("	}\r\n");
      out.write("	function closeOverlayAll(){\r\n");
      out.write("		for(var i=0; i<overlayAry.length; i++){\r\n");
      out.write("			overlayAry[i].setMap(null);\r\n");
      out.write("		}\r\n");
      out.write("	}	\r\n");
      out.write("	\r\n");
      out.write("	function closeOverlay(id) {\r\n");
      out.write("		console.log(\"close!\");\r\n");
      out.write("		//console.log(overlayAry[id]);\r\n");
      out.write("		overlayAry[id].setMap(null);\r\n");
      out.write("	    //overlay.setMap(null);     \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	function addElements(data){\r\n");
      out.write("		var dataOne = data;\r\n");
      out.write("		var list = document.createElement('li');\r\n");
      out.write("		list.setAttribute(\"class\", \"listCh\");\r\n");
      out.write("\r\n");
      out.write("		//여기서 숙소, 음식점, 관광지를 분류하여 출력\r\n");
      out.write("		var cate = dataOne.markerId.substring(0,2);\r\n");
      out.write("		listMake(list, dataOne);\r\n");
      out.write("		mkParents.appendChild(list);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	//필터로 탭을 누르면 해당하는 것만 출력\r\n");
      out.write("	function listFilter(event, dtoList){\r\n");
      out.write("		mkParents.innerHTML =\"\";\r\n");
      out.write("		//console.log(\"event\");\r\n");
      out.write("		//console.log(event);\r\n");
      out.write("		var me = event.target.id;\r\n");
      out.write("		console.log(me);\r\n");
      out.write("		rmAllMarker(baseMarkers);\r\n");
      out.write("		//rmCircleMarker();\r\n");
      out.write("		for(var i=0; i<dtoList.length; i++)\r\n");
      out.write("		{\r\n");
      out.write("			(function(index){\r\n");
      out.write("				//1. 어떤 것을 출력할지 필터부터.\r\n");
      out.write("				var dataOne = dtoList[index];\r\n");
      out.write("				var cate = dataOne.markerId.substring(0,2);\r\n");
      out.write("				if(cate == me){\r\n");
      out.write("				//2. 필터로 걸러진 것만 출력		\r\n");
      out.write("					//console.log(cate);\r\n");
      out.write("					addElements(dataOne);\r\n");
      out.write("					addMarker(cate, dataOne);\r\n");
      out.write("				}else if(cate == me){\r\n");
      out.write("					addElements(dataOne);\r\n");
      out.write("					addMarker(cate, dataOne);\r\n");
      out.write("				}else if(cate == me){\r\n");
      out.write("					addElements(dataOne);\r\n");
      out.write("					addMarker(cate, dataOne);\r\n");
      out.write("				}\r\n");
      out.write("			})(i);	\r\n");
      out.write("		}\r\n");
      out.write("		//inIn = 1;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//마커 삭제하기\r\n");
      out.write("	function rmAllMarker(markers){\r\n");
      out.write("		//console.log(\"markers.length\");\r\n");
      out.write("		//console.log(markers.length);\r\n");
      out.write("		\r\n");
      out.write("		for(var k=0; k<markers.length; k++){\r\n");
      out.write("			markers[k].setMap(null);	\r\n");
      out.write("		}\r\n");
      out.write("		//markers.length = 0;\r\n");
      out.write("		markers = [];\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function markersByCircle(marker, data) {	//marker는 클릭한 마커\r\n");
      out.write("		const radius = 1000; // 반경 1km (미터 단위)\r\n");
      out.write("	    const centerPosition = marker.getPosition();	//마커의 포지션\r\n");
      out.write("		//console.log(\"2. circle make\");\r\n");
      out.write("	    \r\n");
      out.write("	    //원이 존재하면 삭제\r\n");
      out.write("	    if (activeCircle) {\r\n");
      out.write("	        activeCircle.setMap(null);\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    // 원 객체 생성\r\n");
      out.write("	    const circle = new kakao.maps.Circle({\r\n");
      out.write("	        center: centerPosition, // 원의 중심좌표\r\n");
      out.write("	        radius: radius, 		// 반경 (미터 단위)\r\n");
      out.write("	        strokeWeight: 2,\r\n");
      out.write("	        strokeColor: '#75B8FA',\r\n");
      out.write("	        strokeOpacity: 1,\r\n");
      out.write("	        strokeStyle: 'solid',\r\n");
      out.write("	        fillColor: '#CFE7FF',\r\n");
      out.write("	        fillOpacity: 0.5\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    \r\n");
      out.write("	    //클릭한 마커로 화면을 이동하는데 쓰이는 변수\r\n");
      out.write("	    var viewPosition = marker.getPosition();\r\n");
      out.write("	    var bounds = new kakao.maps.LatLngBounds();\r\n");
      out.write("	    \r\n");
      out.write("	    bounds.extend(viewPosition);\r\n");
      out.write("	    var padding = 0.01; // 여백 정도를 설정 (값을 조정해 멀리 보이도록 설정)\r\n");
      out.write("\r\n");
      out.write("	 	// 마커 위치를 기준으로 상하좌우에 약간의 거리 추가\r\n");
      out.write("	 	bounds.extend(new kakao.maps.LatLng(viewPosition.getLat() + padding, viewPosition.getLng() + padding)); // 북동쪽\r\n");
      out.write("		bounds.extend(new kakao.maps.LatLng(viewPosition.getLat() - padding, viewPosition.getLng() - padding)); // 남서쪽\r\n");
      out.write("\r\n");
      out.write("        map.panTo(viewPosition);\r\n");
      out.write("        map.setBounds(bounds);\r\n");
      out.write("        \r\n");
      out.write("	    circle.setMap(map); // 원을 지도에 표시\r\n");
      out.write("	    activeCircle = circle;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	// Haversine 공식에 따른 두 점 간 거리 계산 함수	\r\n");
      out.write("	function haversineDistance(lat1, lon1, lat2, lon2) {\r\n");
      out.write("		const R = 6371;\r\n");
      out.write("	    const toRad = (value) => (value * Math.PI) / 180;\r\n");
      out.write("\r\n");
      out.write("	    //const dLat = Math.abs(lat1-lat2)*toRad;\r\n");
      out.write("	    //const dLon = Math.abs(lon1-lon2)*toRad;\r\n");
      out.write("	    \r\n");
      out.write("	    const dLat = toRad(lat2 - lat1);\r\n");
      out.write("	    const dLon = toRad(lon2 - lon1);\r\n");
      out.write("\r\n");
      out.write("	    const a = Math.sin(dLat / 2) ** 2 +\r\n");
      out.write("	              Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) *\r\n");
      out.write("	              Math.sin(dLon / 2) ** 2;\r\n");
      out.write("\r\n");
      out.write("	    const c = 2 * Math.asin(Math.sqrt(a));\r\n");
      out.write("	    \r\n");
      out.write("	   // console.log(\"math : \" + c);\r\n");
      out.write("	    return R * c; // 거리 (킬로미터)\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("		\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
