/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2024-12-16 06:33:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.Member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.spring.domain.Member;

public final class allMembers_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.spring.domain.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");

	int pageNum = (Integer) request.getAttribute("pageNum");
	int totalPage = (Integer) request.getAttribute("totalPage");
	System.out.println("페이지넘 : " + pageNum);
	System.out.println("토탈페이지 : " + totalPage);

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>전체 회원 관리</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div>전체 회원</div>\r\n");
      out.write("	<div>\r\n");
      out.write("	<a href=\"./allMembers?memberlist=1\">가입 날짜 순</a>\r\n");
      out.write("	<a href=\"./allMembers?memberlist=2\">가나다 순</a>\r\n");
      out.write("		<table border=\"1\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>이메일</th>\r\n");
      out.write("				<th>닉네임</th>\r\n");
      out.write("				<th>성별</th>\r\n");
      out.write("				<th>나이</th>\r\n");
      out.write("				<th>뱃지</th>\r\n");
      out.write("				<th>가입날짜</th>\r\n");
      out.write("				<th></th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");

				List<Member> list = (List<Member>) request.getAttribute("memberList");
				for(int j=0; j<list.size(); j++){
					Member member = list.get(j);
			
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>");
      out.print(member.getEmail());
      out.write("</th>\r\n");
      out.write("				<th>");
      out.print(member.getNickName() );
      out.write("</th>\r\n");
      out.write("				<th>");
      out.print(member.getGender() );
      out.write("</th>\r\n");
      out.write("				<th>");
      out.print(member.getAge() );
      out.write("</th>\r\n");
      out.write("				<th>");
      out.print(member.getBadgeName() );
      out.write("</th>\r\n");
      out.write("				<th>");
      out.print(member.getJoinDay() );
      out.write("</th>\r\n");
      out.write("				<th><a href=\"deleteMember?email=");
      out.print(member.getEmail());
      out.write("\" class=\"btn btn-danger\">삭제</a>\r\n");
      out.write("			</tr>\r\n");
      out.write("		");
} 
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("		");
for(int i=1; i<=totalPage; i++){
      out.write("\r\n");
      out.write("		<a href=\"allMembers?pageNum=");
      out.print(i );
      out.write("\">\r\n");
      out.write("			");
if(pageNum == i){ 
      out.write("\r\n");
      out.write("			<font color='4C5317'><b>[");
      out.print(i);
      out.write("]</b></font>\r\n");
      out.write("			");
}else{ 
      out.write("\r\n");
      out.write("			<font color='4C5317'><b>[");
      out.print(i);
      out.write("]</b></font>\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("		</a>\r\n");
      out.write("		");
} 
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
